### ISSUE TITLE
Font-path not found.

### ISSUE THREAD

**Issue by bherwig** [flxai/pyceau#1]
Starting `pyceau` I get the following stacktrace:
```
Traceback (most recent call last):
  File "./pyceau", line 463, in <module>
    post_rule_string=args.post_rules, post_ticks=args.post_ticks)
  File "./pyceau", line 81, in __init__
    self.font = ImageFont.truetype(self.font_path, self.font_size)
  File "[...]lib/python3.7/site-packages/PIL/ImageFont.py", line 546, in truetype
    return freetype(font)
  File "[...]lib/python3.7/site-packages/PIL/ImageFont.py", line 543, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "[...]lib/python3.7/site-packages/PIL/ImageFont.py", line 161, in __init__
    font, size, index, encoding, layout_engine=layout_engine
OSError: cannot open resource
```
Setting font-path from the cmd-line directly is a workaround.

**Comment by flxai** [comment]
Thanks for reporting. I think I fixed it. Would appreciate a test run from your side. You can also now easily install it via:

```
pip install pyceau
```
